### ISSUE TITLE
panic in installer CLI while trying to use Kubernetes option

### ISSUE THREAD

**Issue by marktheunissen** [kubeshop/tracetest#1516]
**Describe the bug**

I tried to install tracetest using the Kube option, but got a panic in the UI interactive_select_printer, see panic stacktrace below:

**To Reproduce**

```
❯ tracetest server install

Hi! Welcome to the TraceTest server installer. I'll help you set up your TraceTest server by asking you a few questions
and configuring your system with all the requirements, so you can start TraceTesting right away!

To get more info about TraceTest, you can check our docs at https://kubeshop.github.io/tracetest/

If you have any issues, please let us know by creating an issue (https://github.com/kubeshop/tracetest/issues/new/choose)
or reach us on Discord https://discord.gg/6zupCZFQbe


How do you want to run TraceTest?:
  > Using Kubernetes


-> Let's check if your system has everything we need

✔ kubectl already installed
✔ helm already installed
Are you going to run it locally or in a remote cluster?:
  > Locally

Do you have a local kubernentes running? [Y/n]: Yes

-> Your system is ready! Now, let's configure TraceTest

Kubeconfig file [${HOME}/.kube/config]:

panic: runtime error: slice bounds out of range [:31] with capacity 30

goroutine 1 [running]:
github.com/pterm/pterm.(*InteractiveSelectPrinter).Show(0x140001c48c0, {0x0, 0x0, 0x7?})
	/home/runner/go/pkg/mod/github.com/pterm/pterm@v0.12.46/interactive_select_printer.go:116 +0x820
github.com/kubeshop/tracetest/cli/ui.ptermUI.Select({}, {0x10499ea7d, 0xf}, {0x140003a0900, 0x1e, 0x140003a0900?}, 0x1b)
	/home/runner/work/tracetest/tracetest/cli/ui/ui.go:154 +0x198
github.com/kubeshop/tracetest/cli/installer.configureKubernetes({0x140005381e0?, {0x104cc6470?, 0x1052da780?}}, {0x104cc6470, 0x1052da780})
	/home/runner/work/tracetest/tracetest/cli/installer/kubernetes.go:415 +0x130
github.com/kubeshop/tracetest/cli/installer.installer.Configure({{0x10499ac4f, 0xa}, {0x10528ae00, 0x4, 0x4}, {0x10528b4e0, 0x5, 0x5}, 0x104cb6180}, {0x104cc6470, ...})
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:61 +0xd8
github.com/kubeshop/tracetest/cli/installer.installer.Install({{0x10499ac4f, 0xa}, {0x10528ae00, 0x4, 0x4}, {0x10528b4e0, 0x5, 0x5}, 0x104cb6180}, {0x104cc6470, ...})
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:72 +0x150
github.com/kubeshop/tracetest/cli/installer.Start()
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:38 +0x27c
github.com/kubeshop/tracetest/cli/cmd.glob..func3(0x105297aa0?, {0x1052dab40?, 0x0?, 0x0?})
	/home/runner/work/tracetest/tracetest/cli/cmd/server_install_cmd.go:21 +0x90
github.com/spf13/cobra.(*Command).execute(0x105297aa0, {0x1052dab40, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x1052975a0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/kubeshop/tracetest/cli/cmd.Execute()
	/home/runner/work/tracetest/tracetest/cli/cmd/root.go:30 +0x2c
main.main()
	/home/runner/work/tracetest/tracetest/cli/main.go:8 +0x20
```

**Expected behavior**

No panic, installer continues

**Additional context**

I was also unable to get the docker compose install working, the container just didn't start up (postgres was fine, though). 

**Further thoughts**

As a new user who has experience deploying apps in Kube, docker, etc, I was frustrated by the installer wizard in general, and would prefer to just get sample manifests (helm charts / docker compose) or clear description of how to setup the pieces myself. 

The wizard is trying to do too much that should be out of scope - I can see code here that will attempt to install minikube if it isn't available - surely this is going too far?

**Comment by schoren** [comment]
@marktheunissen thanks for the feedback. I'll try to fix the installer ASAP, but if you rather do a direct helm install, you can use our charts (It's not very documented yet).

https://github.com/kubeshop/helm-charts/tree/main/charts/tracetest

You would need to configure the tracetest settings related to your [otel-collector](https://github.com/kubeshop/helm-charts/blob/main/charts/tracetest/values.yaml#L64) and [tracing backend
](https://github.com/kubeshop/helm-charts/blob/main/charts/tracetest/values.yaml#L37).

The idea of our installer is to help people getting started in the otel tracing world. It can be intimidating connecting all those pieces together. But if you have more experience, using the helm chart directly is probably more flexible.

As an additional resource, you can always ping us on [Discord](https://discord.gg/6zupCZFQbe)

**Comment by kdhamric** [comment]
Appreciate your filing the issue @marktheunissen! We just released v0.8 late yesterday, and are beginning planning on 0.9. One of the big goals will be to ease 'first use' experience, through installer, documentation, and possibly product changes. Will keep you updated as we go and may ask for your thoughts on our direction on this if you are willing.
