### ISSUE TITLE
[data source] Tempo - Issue with HTTP connection

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#2166]
**Describe the bug**
When connecting Tracetest to the HTTP endpoint of Tempo it causes a server panic.

```
quick-start-tempo-nodejs-tempo-1           | level=info ts=2023-03-15T14:18:48.213300513Z caller=handler.go:119 tenant=single-tenant method=GET traceID=188170d8ec438a65 url=/api/traces/28c9794fae17a9e2dbcc1f5c6b7996c7 duration=19.455125ms response_size=0 status=404
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:48 [PollerExecutor] Test QoB91LaVR Run 4: GetTraceByID (traceID 28c9794fae17a9e2dbcc1f5c6b7996c7) error: trace not found
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:48 [TracePoller] Test QoB91LaVR Run 4: ExecuteRequest Error: trace not found
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:48 [TracePoller] Trace not found on Data Store yet. Requeuing...
quick-start-tempo-nodejs-tracetest-1       | [TracePoller] Requeuing Test Run 4. Current iteration: 0
quick-start-tempo-nodejs-tracetest-1       | sending event "Get Test Version" (test)
quick-start-tempo-nodejs-tracetest-1       | event sent "Get Test Version" (test)
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:48 GET /api/tests/QoB91LaVR/version/1 GetTestVersion 7.750708ms
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:53 [TracePoller] Test QoB91LaVR Run 4: Received job
quick-start-tempo-nodejs-tracetest-1       | 2023/03/15 14:18:53 [PollerExecutor] Test QoB91LaVR Run 4: ExecuteRequest
quick-start-tempo-nodejs-tempo-1           | level=info ts=2023-03-15T14:18:53.274440084Z caller=handler.go:119 tenant=single-tenant method=GET traceID=2ddc22949b6440a9 url=/api/traces/28c9794fae17a9e2dbcc1f5c6b7996c7 duration=36.974333ms response_size=1930 status=200
quick-start-tempo-nodejs-tracetest-1       | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
quick-start-tempo-nodejs-tracetest-1       | 	panic: runtime error: invalid memory address or nil pointer dereference
quick-start-tempo-nodejs-tracetest-1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x467a5e]
quick-start-tempo-nodejs-tracetest-1       |
quick-start-tempo-nodejs-tracetest-1       | goroutine 44 [running]:
quick-start-tempo-nodejs-tracetest-1       | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:393 +0x2a
quick-start-tempo-nodejs-tracetest-1       | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00062a480, {0x0, 0x0, 0xc0008121e0?})
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:432 +0x8ee
quick-start-tempo-nodejs-tracetest-1       | panic({0x1858c20, 0x2ce7590})
quick-start-tempo-nodejs-tracetest-1       | 	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x212
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/model.NewTrace({0x0, 0x0}, {0xc0007cc0e0, 0x0, 0x16b055c?})
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/model/traces.go:42 +0x30f
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/traces.FromHttpOtelResourceSpans({0xc000046500, 0x2, 0x4000803a68?})
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/traces/otel_http_converter.go:61 +0x30b
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/tracedb.httpGetTraceByID({0x1ecb760, 0xc00036be90}, {0xc0000ace40?, 0xc00056e680?}, 0xc00062a600?)
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/tracedb/tempodb.go:145 +0x3a5
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/tracedb/datasource.(*HttpClient).GetTraceByID(0x8?, {0x1ecb760?, 0xc00036be90?}, {0xc0000ace40?, 0x4?})
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/tracedb/datasource/http.go:61 +0xb3
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/tracedb.(*tempoTraceDB).GetTraceByID(0x342949786ad4129f?, {0x1ecb760?, 0xc00036be90?}, {0xc0000ace40?, 0x0?})
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/tracedb/tempodb.go:71 +0xa8
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/executor.DefaultPollerExecutor.ExecuteRequest({{_, _}, _, {_, _}, _}, _)
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/executor/poller_executor.go:106 +0x42c
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/executor.InstrumentedPollerExecutor.ExecuteRequest({{_, _}, {_, _}}, _)
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/executor/poller_executor.go:34 +0x191
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/executor.tracePoller.processJob({{0x1ec0840, 0xc0000a9650}, {0x1ebd6e0, 0xc000047600}, 0x8bb2c97000, {0x1ec7970, 0xc0006b6000}, 0x12a05f200, 0x78, 0xc00032c030, ...}, ...)
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/executor/trace_poller.go:129 +0xd4
quick-start-tempo-nodejs-tracetest-1       | github.com/kubeshop/tracetest/server/executor.tracePoller.Start.func1()
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/executor/trace_poller.go:104 +0x1b8
quick-start-tempo-nodejs-tracetest-1       | created by github.com/kubeshop/tracetest/server/executor.tracePoller.Start
quick-start-tempo-nodejs-tracetest-1       | 	/home/runner/work/tracetest/tracetest/server/executor/trace_poller.go:95 +0x29
quick-start-tempo-nodejs-tracetest-1 exited with code 2
```

**To Reproduce**
1. Run https://github.com/kubeshop/tracetest/tree/main/examples/quick-start-tempo-nodejs 
2. Configure Tempo to use HTTP endpoint

![localhost_11633_settings (8)](https://user-images.githubusercontent.com/15029531/225340367-d72eba5a-f750-4776-b70a-dbc1d5ff8b10.png)

3. Run a test
4. See error in terminal

**Expected behavior**
Server should not trigger panic.

**Comment by xoscar** [comment]
Figured out the problem, and applied a solution
