### ISSUE TITLE
CLI randomly crashes in a transaction reporting

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2483]
When running a transaction test, sometimes we receive a `index out of range` error on both error and successful cases. 

This happens because we assume that we will receive the same size of test results and specs, which is not happening. We need to understand why this assumption is broken on recent versions of tracetest.

Error message:

```sh
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/kubeshop/tracetest/cli/formatters.testRun.formatFailedTest({{{_, _}, {_, _}, _, _}, _, _}, {0xc000473d80, 0xc000473d90, ...}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:185 +0xc25
github.com/kubeshop/tracetest/cli/formatters.testRun.pretty({{{_, _}, {_, _}, _, _}, _, _}, {0x1, {0xc000473d80, ...}, ...})
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:99 +0x5de
github.com/kubeshop/tracetest/cli/formatters.transactionRun.pretty({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0x1, {{{0xc00045ce10, 0x4}, {0xc00045ce30, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:99 +0x74a
github.com/kubeshop/tracetest/cli/formatters.transactionRun.Format({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0x1, {{{0xc00045ce10, 0x4}, {0xc00045ce30, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:38 +0x319
github.com/kubeshop/tracetest/cli/actions.runTestAction.transactionRun({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0xc000457f80, 0xc000462480}, {0x18b1fe8, 0xc00009e000}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:439 +0x545
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinitionFile({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0xc000457f80, 0xc000462480}, {0x18b1fe8, 0xc00009e000}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:309 +0x1885
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinition({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0xc000457f80, 0xc000462480}, {0x18b1fe8, 0xc00009e000}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:201 +0x2dc
github.com/kubeshop/tracetest/cli/actions.runTestAction.Run({{{0xc00045ce10, 0x4}, {0xc00045ce30, 0xf}, 0x0, 0x0}, 0xc000457f80, 0xc000462480}, {0x18b1fe8, 0xc00009e000}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:85 +0x674
github.com/kubeshop/tracetest/cli/cmd.glob..func19(0x1d7f320?, {0xc000457f10?, 0x0?, 0x7?})
        /home/runner/work/tracetest/tracetest/cli/cmd/test_run_cmd.go:40 +0x2ea
github.com/spf13/cobra.(*Command).execute(0x1d7f320, {0xc000457ea0, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1d7d0a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubeshop/tracetest/cli/cmd.Execute()
        /home/runner/work/tracetest/tracetest/cli/cmd/root.go:33 +0x25
main.main()
        /home/runner/work/tracetest/tracetest/cli/main.go:8 +0x17
```

**Comment by danielbdias** [comment]
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/kubeshop/tracetest/cli/formatters.testRun.formatSuccessfulTest({{{_, _}, {_, _}, _, _}, _, _}, {0xc00005f8e0, 0xc00005f8f0, ...}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:114 +0x6e7
github.com/kubeshop/tracetest/cli/formatters.testRun.pretty({{{_, _}, {_, _}, _, _}, _, _}, {0x1, {0xc00005f8e0, ...}, ...})
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:102 +0x51e
github.com/kubeshop/tracetest/cli/formatters.transactionRun.pretty({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0x1, {{{0xc00043d8f0, 0x4}, {0xc00043d910, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:99 +0x74a
github.com/kubeshop/tracetest/cli/formatters.transactionRun.Format({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0x1, {{{0xc00043d8f0, 0x4}, {0xc00043d910, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:38 +0x319
github.com/kubeshop/tracetest/cli/actions.runTestAction.transactionRun({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0xc00043ff10, 0xc00043a700, {{0xc00043ff10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:374 +0x4c5
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinitionFile({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0xc00043ff10, 0xc00043a700, {{0xc00043ff10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:244 +0x1765
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinition({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0xc00043ff10, 0xc00043a700, {{0xc00043ff10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:136 +0x2a8
github.com/kubeshop/tracetest/cli/actions.runTestAction.Run({{{0xc00043d8f0, 0x4}, {0xc00043d910, 0xf}, 0x0, 0x0}, 0xc00043ff10, 0xc00043a700, {{0xc00043ff10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:96 +0x71f
github.com/kubeshop/tracetest/cli/cmd.glob..func19(0x1dad720?, {0xc00044a320?, 0x0?, 0x5?})
        /home/runner/work/tracetest/tracetest/cli/cmd/test_run_cmd.go:44 +0x5ca
github.com/spf13/cobra.(*Command).execute(0x1dad720, {0xc00044a2d0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1dab1c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubeshop/tracetest/cli/cmd.Execute()
        /home/runner/work/tracetest/tracetest/cli/cmd/root.go:33 +0x25
main.main()
        /home/runner/work/tracetest/tracetest/cli/main.go:8 +0x17

**Comment by danielbdias** [comment]
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/kubeshop/tracetest/cli/formatters.testRun.formatFailedTest({{{_, _}, {_, _}, _, _}, _, _}, {0xc00039a5c0, 0xc00039a5d0, ...}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:185 +0xc25
github.com/kubeshop/tracetest/cli/formatters.testRun.pretty({{{_, _}, {_, _}, _, _}, _, _}, {0x1, {0xc00039a5c0, ...}, ...})
        /home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:99 +0x5de
github.com/kubeshop/tracetest/cli/formatters.transactionRun.pretty({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0x1, {{{0xc0003f7870, 0x4}, {0xc0003f7890, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:99 +0x74a
github.com/kubeshop/tracetest/cli/formatters.transactionRun.Format({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0x1, {{{0xc0003f7870, 0x4}, {0xc0003f7890, ...}, ...}, ...}}, ...)
        /home/runner/work/tracetest/tracetest/cli/formatters/transaction_run.go:38 +0x319
github.com/kubeshop/tracetest/cli/actions.runTestAction.transactionRun({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0xc0003f9f10, 0xc0003f46c0, {{0xc0003f9f10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:374 +0x4c5
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinitionFile({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0xc0003f9f10, 0xc0003f46c0, {{0xc0003f9f10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:244 +0x1765
github.com/kubeshop/tracetest/cli/actions.runTestAction.runDefinition({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0xc0003f9f10, 0xc0003f46c0, {{0xc0003f9f10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:136 +0x2a8
github.com/kubeshop/tracetest/cli/actions.runTestAction.Run({{{0xc0003f7870, 0x4}, {0xc0003f7890, 0xf}, 0x0, 0x0}, 0xc0003f9f10, 0xc0003f46c0, {{0xc0003f9f10, {{...}, ...}, ...}}}, ...)
        /home/runner/work/tracetest/tracetest/cli/actions/run_test_action.go:96 +0x71f
github.com/kubeshop/tracetest/cli/cmd.glob..func19(0x1dad720?, {0xc0004062d0?, 0x0?, 0x5?})
        /home/runner/work/tracetest/tracetest/cli/cmd/test_run_cmd.go:44 +0x5ca
github.com/spf13/cobra.(*Command).execute(0x1dad720, {0xc000406280, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1dab1c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubeshop/tracetest/cli/cmd.Execute()
        /home/runner/work/tracetest/tracetest/cli/cmd/root.go:33 +0x25
main.main()
        /home/runner/work/tracetest/tracetest/cli/main.go:8 +0x17
