### ISSUE TITLE
Missing trace error handling

### ISSUE THREAD

**Issue by povilasv** [kubeshop/tracetest#63]
Sometime system under test fails to produce a trace due to various reasons.

How do we handle this case?

Example, app failed to send trace to otel collector:

```

2022/03/01 10:07:50 http: panic serving 10.42.0.25:44246: rpc error: code = Unavailable desc = error reading from server: EOF
goroutine 188 [running]:
net/http.(*conn).serve.func1(0xc0005000a0)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0xa5e6a0, 0xc000010020)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000702900, 0x0, 0x0, 0x0)
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.3.0/trace/span.go:282 +0x345
panic(0xa5e6a0, 0xc000010020)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000280900, 0x0, 0x0, 0x0)
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.3.0/trace/span.go:282 +0x345
panic(0xa5e6a0, 0xc000010020)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
main.(*povService).httpHandler(0xc0001c9440, 0xbd23e0, 0xc00048b740, 0xc000594500)
        /src/main.go:85 +0xceb
net/http.HandlerFunc.ServeHTTP(0xc0003a0b90, 0xbd23e0, 0xc00048b740, 0xc000594500)
        /usr/local/go/src/net/http/server.go:2042 +0x44
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc0001ccdc0, 0xbd23e0, 0xc00048b740, 0xc000594000)
        /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.28.0/handler.go:189 +0x977
net/http.(*ServeMux).ServeHTTP(0xf8fc40, 0xbd15e0, 0xc00043c000, 0xc000594000)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0003e0000, 0xbd15e0, 0xc00043c000, 0xc000594000)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0005000a0, 0xbd2ce0, 0xc000400040)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Comment by kdhamric** [comment]
@schoren @mathnogueira Should we leave this issue open or close it?  I know we have done some work on the states since this was written - did that resolve it / provide us with a solution for the short term.  We will likely put more energy into this area as we move ahead, but are we 'ok' for now?

**Comment by schoren** [comment]
Right now we log errors in all processes as a way of handling them. I think this refers to what happens when we cannot get a trace for whatever reason. This would also apply for traces ignored by sampling etc. 
I think this is an issue that we need to solve, but as a more general “handle missing trace” thing

**Comment by kdhamric** [comment]
Ok - I am going to add it to the MVPrototype and put it into the backlog.  If we need to pull it out / deprioritize it until later, no problem.

**Comment by xoscar** [comment]
@schoren @kdhamric is this still actual? or should we remove it from the project?

**Comment by mathnogueira** [comment]
I'm closing it
